Region: us-west-2

S3:
  bucket: ingds-datalakep

SQS:
  url: https://sqs.us-west-2.amazonaws.com/076942521279/datalakep-queue
  waittime: 20
  maxmessages: 10

Redshift:
  name: redshift-datalakep-cluster
  db_name: transcripted
  user: dlp_admin
  password: axUMOgZgOfOsY7J4yHfO
  arn: arn:aws:redshift:us-west-2:076942521279:namespace:34ecd63c-dc87-483f-8bcc-c7e5b3144d75
  port: 5439
  iam_role: arn:aws:iam::076942521279:role:/RedshiftS3AccessRole
  endpoint: redshift-datalakep-cluster-exposed.chqburshgayp.us-west-2.redshift.amazonaws.com

SecretsManager:
  secret_name: datalakep

Tags:
  Proyecto: datalakep