Region: us-west-2

S3:
  bucket: ingds-datalakep

Redshift:
  name: redshift-datalakep-cluster
  db_name: transcripted
  user: dlp_admin
  password: axUMOgZgOfOsY7J4yHfO
  arn: arn:aws:redshift:us-west-2:076942521279:namespace:13b5ddc9-2891-4182-a2b4-327e13dc5aef
  port: 5439
  iam_role: arn:aws:iam::076942521279:role:/RedshiftS3AccessRole
  endpoint: redshift-datalakep-cluster-exposed.chqburshgayp.us-west-2.redshift.amazonaws.com:5439/transcripted

SecretsManager:
  secret_name: datalakep

Tags:
  Proyecto: datalakep